project:
  type: website
  output-dir: docs

website:
  title: "Jose's Portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/munizjos/Projects.git
      - icon: LinkedIn
        href: https://www.linkedin.com/in/jose-b-muniz-rangel-885915246
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

